\ProvidesClass{/home/nyaucki/Documents/Prof/CoursMaths/mycls/DevoirMaison}

\LoadClass[a4paper,12pt]{/home/nyaucki/Documents/Prof/CoursMaths/mycls/ArticleCommande}


\everymath{\displaystyle\everymath{}}
\geometry{margin=1cm}

\geometry{bottom=1.5cm}
\fancypagestyle{plain}{
\setlength{\footskip}{1.2cm}
\renewcommand{\footrulewidth}{0pt}
\renewcommand{\headrulewidth}{0pt}
\lhead{}
\chead{}
\rhead{}
\rfoot{}
\cfoot{}
\lfoot{}
}
\pagestyle{plain}
%%%%%%%%%%%%%% COULEURS %%%%%%%%%%%%%%%%%%%



%%%%%%%%%%%%%%% COMMANDES %%%%%%%%%%%%%%%%%%%%%

\newcommand{\nom}{} 

\newcommand{\prenom}{}

\newcommand{\filling}[1][2cm]{\makebox[#1]{\dotfill}}


